### ISSUE TITLE
Other opts not passed to hybrid swarm

### ISSUE THREAD

**Issue by joehand** [karissa/hyperdrive-archive-swarm#17]
Right now opts not used in datland-swarm-defaults are [discarded here](https://github.com/karissa/hyperdrive-archive-swarm/blob/master/index.js#L25). datland-swarm-defaults only takes one argument. 

I'm not sure it makes sense to add the second argument to datland-swarm-defaults just to extend the object. But happy to do that if that'd made more sense.

For now, the only extra option is `opts.wrtc`. So we could just set that:

``` js
  var hybridOpts = {
    signalhub: signalhub(swarmKey, opts.signalhub || DEFAULT_SIGNALHUB),
    discovery: swarmDefaults({
      id: archive.id,
      hash: false,
      stream: function (peer) {
        return archive.replicate()
      }
    }),
   wrtc: opts.wrtc
  }
```

I can open a PR, just had this in my head and needed to write it down =). Wasn't sure if the opts on line 25 was trying to do something else as well.

**Comment by okdistribute** [comment]
Good question. It makes sense to have a wrtc option, if you think it's the easier path.
