### ISSUE TITLE
is there a way to stop swarming?

### ISSUE THREAD

**Issue by pfrazee** [karissa/hyperdrive-archive-swarm#2]
After I've got the archive, I may want to drop out of the swarm

**Comment by okdistribute** [comment]
yeah good point!

**Comment by lukeburns** [comment]
yes please!

**Comment by juliangruber** [comment]
@mafintosh and me were talking about an api like `.add(archive)` and `.remove(archive)`, for managing multiple archives in one swarm. once `.remove(archive)` implements a logic to stop, the `.stop()` function could just call `.remove` on all archives.

**Comment by okdistribute** [comment]
Now this is using discovery-swarm directly which has a join and leave function built-in.
