### ISSUE TITLE
prune deps

### ISSUE THREAD

**Issue by mafintosh** [karissa/hyperdrive-archive-swarm#22]
seems a lot of npm install is spent installing this (especially the webrtc deps).

it might be a good idea to split that out into a different thing as those aren't used most of the time anyway

**Comment by okdistribute** [comment]
ok good deal!

**Comment by okdistribute** [comment]
Fixed in 5.0.1. Major release bump that removes webrtc-swarm stuff altogether.

The api has changed slightly, too -- now it just returns the discovery-swarm instance, so you have to do `swarm.connections.length`  instead of `swarm.connections`

**Comment by joehand** [comment]
yay!
