### ISSUE TITLE
use webrtc if it's available (electron)

### ISSUE THREAD

**Issue by pfrazee** [karissa/hyperdrive-archive-swarm#3]
This is something @mafintosh pointed out --

Electron can use webrtc and discovery-swarm, and it'd be good to use both so the browser-folk can be reached

**Comment by juliangruber** [comment]
+1

**Comment by okdistribute** [comment]
I think it should already work and use both on electron, let me know or feel free to open PR to fix that if not, it should do that!

**Comment by juliangruber** [comment]
electron doesn't have `process.browser = true`, maybe detecting something like detecting the presence of the window object and the webrtc api would work. i'll come up with a pr

**Comment by mafintosh** [comment]
I do this in the dat cli now. @juliangruber feel free to steal some of that code. At some point cli should switch to use this module

**Comment by okdistribute** [comment]
nice catch
